name: 'pnpm installation'
description: 'Install and audit dependencies via pnpm'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      with:
        version: 9.4.0

    - name: Setup node
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
      with:
        node-version: 22.12
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

## Usage
# - name: install and audit
#   uses: ./.github/actions/pnpm
#   with:
#     version: ${{ env.PNPM_VERSION }}
