name: Build Docker Images

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-docker-images:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        nodeVersion: [
          22.13.0,
          20.18.1,
          18.20.5,
          16.20.2,
          14.21.3
        ]
    steps:
      - name: Checkout code repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Extract node major version to tag docker image
        run: echo "NODE_TAG=$(cut -d '.' -f 1 <<< ${{ matrix.nodeVersion }})" >> $GITHUB_ENV

      - name: Verify docker builds all images
        # if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          sh docker/build.sh ${{ matrix.nodeVersion }}
          docker images --filter=reference="electronuserland/builder:*"
          docker save -o ${{ runner.temp }}/electron-builder-all-${{ env.NODE_TAG }}.tar electronuserland/builder

      - name: Bundle all images
        # if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: electron-builder-all-${{ env.NODE_TAG }}
          path: ${{ runner.temp }}/electron-builder-all-${{ env.NODE_TAG }}.tar
          retention-days: 1
          if-no-files-found: error